language: node_js
node_js:
- 0.12.1
before_script:
- npm install -g bower karma grunt-cli
- npm install
- bower install
after_script:
- grunt
- codeclimate-test-reporter < test/coverage/report-lcov/lcov.info
notifications:
  slack:
    secure: bN8pDjPTLTBCixI+HAMeHupFOGVHUC+yjt4r8TNQ53UmOzkracBKTg8oNRYcG+ThhpXcW9JrCAbSJXWNMVVTL57xpreWggrSGkiLSgIIUgAIIsYyja/UZtDGIIwqounpvpJB3d4Iwj1mRCoXXILxeBTSAYz1hdpOsNaAA6r73IwybRflQWF7cVyccp5BdQw7QDJyjkkSRkN08N/PLN7Ih/k6tf0daLo7hwaSwyY85B8wpg3EHlF/cYFhESvbeT1W/B2n5LfAQweGdwWopxED98uUG/oHTuhrmWLA7oEDZeE60pjmgbMRRS4rHWBokYfadt/LFyZv+2uRvSP1cWZ5m6VDGEIlhPS0d+Q3kW3gN4W9mn5FRjywmFU+CNRMh8Y1qQrVhj09O7Z8zEN6srAP5UVZ4SKlbImDOdgpgE3lx+t3G+sLNpJGcI7TsBvmnkHa/CBPGJCplCXrAdbh20ZBXRZP79UsHJXS6Q61WptZrf4cyDwFU0qWerMbHq+BXrQHszxkM7wS28VlSUI0/iw4jf4+roz+TIDm4rIz8dWX/RijIDFYJ8lwA7dddZThmlPdB8dR8IRAE8vvIjnV+9HinqoRwVgh8dEDxn0O1izG7E5KkU6uUZTv4wqcMGcuo0qsAI/nC9nahkxwpxtV/dmSZtzp5vG0i3uU9M1wu/6xs34=
addons:
  code_climate:
    repo_token:
      secure: XdvBgo0XEMonsobpM50gsbg/pNgpyQ9yt8wNP9LMaTPwIjZOSxbNsDS7lWkSZYhI0Z3at7RF6fSsIvejFdd0miXd2exk9VOx5IcD8WZO0Zw1OUPFmPA+bLVnM5pTHJSsBiT6PM1CF0Cb2vBbrITErWWY/7qp+mNxsEmVjhqS8qnWiKddeB0vym0Cqs10TThT6BRyEwl7XF5OrsZibApXG6vxCCT8IFzu85OJxzfkuR4kklhqU1OEfrEJqt8dH0I9gOKeQJqXgB2dv6qozvY19Fn3TMkLR+A5pCZ0/hM4NnN3Nqvv1baZMuVoorU94gpDgGW4rVpt9gOJxY/VUuqGA0CObmPnZp5dXRRcdtmxawGKxSR4cTtYowHVWs3hOYRvwac2xsij0OfbhkPCZz7ujGh/AMP1Hwk8+GuvWfOxLSUfkzDj0QMmk2ju2WlsT908qHzB2m0HvU8hJees2+g5gxoc2ak9mwui1pdn161jM0//0eVdsJcAJM43oBPlgAg4FCQJJjx/Wc23gGXPRhrLvJ9zq4izDBpxW+dIh/28lNv5QWMtTeMCARg1Xw9iGTusQy2v4DSV6dXd3td6AtXDvVjHX7f3R1//Rg/bdqGsn3VP3pNxFAv2fiRdVu07uvirj2dy9lyXg/QOuKaAYW+yzG7Dr2v1i2r712fF6PTozfo=