language: node_js
node_js:
- 0.12.1
before_script:
- npm install -g bower karma grunt-cli
- npm install
- bower install
after_script:
- grunt
notifications:
  slack:
    secure: bN8pDjPTLTBCixI+HAMeHupFOGVHUC+yjt4r8TNQ53UmOzkracBKTg8oNRYcG+ThhpXcW9JrCAbSJXWNMVVTL57xpreWggrSGkiLSgIIUgAIIsYyja/UZtDGIIwqounpvpJB3d4Iwj1mRCoXXILxeBTSAYz1hdpOsNaAA6r73IwybRflQWF7cVyccp5BdQw7QDJyjkkSRkN08N/PLN7Ih/k6tf0daLo7hwaSwyY85B8wpg3EHlF/cYFhESvbeT1W/B2n5LfAQweGdwWopxED98uUG/oHTuhrmWLA7oEDZeE60pjmgbMRRS4rHWBokYfadt/LFyZv+2uRvSP1cWZ5m6VDGEIlhPS0d+Q3kW3gN4W9mn5FRjywmFU+CNRMh8Y1qQrVhj09O7Z8zEN6srAP5UVZ4SKlbImDOdgpgE3lx+t3G+sLNpJGcI7TsBvmnkHa/CBPGJCplCXrAdbh20ZBXRZP79UsHJXS6Q61WptZrf4cyDwFU0qWerMbHq+BXrQHszxkM7wS28VlSUI0/iw4jf4+roz+TIDm4rIz8dWX/RijIDFYJ8lwA7dddZThmlPdB8dR8IRAE8vvIjnV+9HinqoRwVgh8dEDxn0O1izG7E5KkU6uUZTv4wqcMGcuo0qsAI/nC9nahkxwpxtV/dmSZtzp5vG0i3uU9M1wu/6xs34=
