# whitelist
branches:
  only:
    - master
sudo: required
services: 
  - docker
language: node_js
node_js:
  - 4.4.3
before_script:
  - npm install -g bower karma grunt-cli
  - npm install
  - bower install
after_success:
  - ls -alth
  - docker build -t matchbox/nci-match-ui .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag -f matchbox/nci-match-ui matchbox/nci-match-ui:latest
  - docker images
  - docker push matchbox/nci-match-ui
   #Deploy to AWS IntTest
  - docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy --cluster PedMatch-IntTest --service-name uMatch-nci-match-ui-INTTEST -i matchbox/nci-match-ui:latest
  #Trigger Travis bdd tests
  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json" -H "Travis-API-Version:3" -H "Authorization:token $TRAVIS_TOKEN" -d "{\"request\":{\"message\":\"Triggered by nci-match-ui $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=nci-match-ui;CUC_TAG=@ui\"]}}}}" https://api.travis-ci.org/repo/CBIIT%2Fnci-uMatch-bddtests/requests
after_script:
  - codeclimate-test-reporter < test/coverage/report-lcov/lcov.info
notifications:
  slack:
    secure: TjBZ1IiNBbjWYJvjCxgtvzzjlomJFor+b2VOAshjWq2iXuryZB1YjGFeI3DuCorLN8KjFazORVLT+div1mEeKuJ2My7pF0qXrNEGgMpAkyCNX4xvVCEGYCVx7vzHGcdMoiT8ojF4aJBnAcyiLbn03f0zina7jDAdkmS0UovjeZ25+24IlSQ8jEg5Ju0e8MD9woMxgiLNqpu+teZiYgLnHOeodVZnRyhUqqQ6FuFsJXKlNvhIrG6oEo3rXB9xtZ4v0yQU0BYW5w/Pa4vbC2unEzoA66gZAWkiaI4nO8jszi84rEU/X8VPYK1IyQPPYvqGI3LZF/a41xgla/TCt0DOzhcgkw7QrQJeZfwj5kxs/YoejDPIsxq4JSBWHgyaGq/n5n1C/nJrEyjRj70PNEyPBnLkivJUZxf3qdC/yVC2iWbo7E2g8Ov7XKfhnHKKnXzjI8XCSFdHr589DSvofKWorJMzu0LzzVbeMyaumdBHfCC2xPH63uLnVT/TIKMu/Dnpr4FibPBhuOlDr1cnyyMuywwB4mJ6Pc8OUElUEMWlOK0zzfTAOeTUWb1IHteVX22Gmre+aUy3VzazGgN1YS7WUygCzYqSZGr3XwUeMiJr9fUy5quxDet4zRx96p3rtnfX6wYFFZ3Bq821dhcHghQf5N0Rt+lgLZfYFWT+b3wtc+w=
addons:
  code_climate:
    repo_token:
      secure: XdvBgo0XEMonsobpM50gsbg/pNgpyQ9yt8wNP9LMaTPwIjZOSxbNsDS7lWkSZYhI0Z3at7RF6fSsIvejFdd0miXd2exk9VOx5IcD8WZO0Zw1OUPFmPA+bLVnM5pTHJSsBiT6PM1CF0Cb2vBbrITErWWY/7qp+mNxsEmVjhqS8qnWiKddeB0vym0Cqs10TThT6BRyEwl7XF5OrsZibApXG6vxCCT8IFzu85OJxzfkuR4kklhqU1OEfrEJqt8dH0I9gOKeQJqXgB2dv6qozvY19Fn3TMkLR+A5pCZ0/hM4NnN3Nqvv1baZMuVoorU94gpDgGW4rVpt9gOJxY/VUuqGA0CObmPnZp5dXRRcdtmxawGKxSR4cTtYowHVWs3hOYRvwac2xsij0OfbhkPCZz7ujGh/AMP1Hwk8+GuvWfOxLSUfkzDj0QMmk2ju2WlsT908qHzB2m0HvU8hJees2+g5gxoc2ak9mwui1pdn161jM0//0eVdsJcAJM43oBPlgAg4FCQJJjx/Wc23gGXPRhrLvJ9zq4izDBpxW+dIh/28lNv5QWMtTeMCARg1Xw9iGTusQy2v4DSV6dXd3td6AtXDvVjHX7f3R1//Rg/bdqGsn3VP3pNxFAv2fiRdVu07uvirj2dy9lyXg/QOuKaAYW+yzG7Dr2v1i2r712fF6PTozfo=
